login/urls.py
from django.urls import path
from . import views

"""
Stores the urls paths for the user
"""

app_name = 'user_auth'
urlpatterns = [
  path('', views.user_login, name='login'),
  path('authenticate_user/', views.authenticate_user, name="authenticate_user"),
]

online_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('django.contrib.auth.urls')),
    path('login/', include('login.urls')),
    path('', include('store.urls')),
    path('register/', include('register.urls')),
]

register/urls.py
from django.urls import path
from . import views

app_name='register'
urlpatterns = [
  path('', views.register, name="register"),
]

store/urls.py
from django.urls import path
from . import views

app_name = "store"
urlpatterns = [
  path('', views.store, name="store"),
  path('cart/', views.cart, name="cart"),
  path('checkout/', views.checkout, name="checkout"),
  path('update_item/', views.updateItem, name="update_item"),
  path('process_order/', views.processOrder, name="process_order"),
]

login/models.py
from django.db import models

# Create your models here.

register/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class Customer(models.Model):
   """
   Model created to store the customer's/user's details
   """
   user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
   name = models.CharField(max_length=200)
   email = models.CharField(max_length=200)

   def __str__(self):
      return self.name

class Product(models.Model):
    """
    Model created to store the product
    """
    name = models.CharField(max_length=200)
    price = models.FloatField()
    created = models.DateTimeField('date published', auto_now_add=True)
    image_link = models.URLField(default="https://placehold.co/600x400/png")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
       return self.name


class Order(models.Model):
  """
  Model created to store the user's orders
  """
  customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
  order_complete = models.BooleanField(default=False)
  order_id = models.CharField(max_length=200, default=0)

  def __str__(self):
      return str(self.id)
  
  @property
  def get_total(self):
     items = self.orderitem_set.all()
     total = sum([item.get_total() for item in items])
     return total
  
  def get_amount(self):
     items = self.orderitem_set.all()
     return len(items)

  
class OrderItem(models.Model):
  """
  Model created to store the ordered item
  """
  product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
  order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)

  def get_total(self):
    return self.product.price

register/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
  """
  Add inputs to the register form with UserCreationForm
  """
  email = forms.EmailField()
  name = forms.CharField()

  class Meta:
    model = User
    fields = [
      "name",
      "username",
      "email",
      "password1",
      "password2",
    ]

login/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect

# Create your views here.

def user_login(request):
    """
    Send a login form back to the user

    :param obj request: The user details

    :returns: the login form
    """
    return render(request, 'authentication/login.html')


# Check if user typed the rigth credentials
def authenticate_user(request):
    """
    Check the user's credentials and login if correct
    or send the login form back if incorrect

    :param obj request: The user details

    :returns: if valid, will return the store page. If not, will return the login page
    """
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(
            reverse('user_auth:login')
        )
    else:
        login(request, user)
        # return reverse('store')
        return HttpResponseRedirect(
            reverse('store:store')
        )

register/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth import login, authenticate
# from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm
from django.contrib.auth import login
from .models import *


# Register the user
def register(request):
  """
  Send a registration form to the user
  if the form is valid, log the user in and
  save the credentials so the user can login
  later. If not, send the form again.

  :param obj request: The user details
  
  :returns: If invalid, will return the register page
  """
  if request.method == "POST":
    form = RegisterForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, form.save())

      return redirect('../')
  else:
    form = RegisterForm()

  return render(request, "register/register.html", { "form": form })

store/views.py
from django.shortcuts import render, redirect
from .models import *
from django.http import JsonResponse
import json
import datetime
from django.urls import reverse



# Create your views here.

def store(request):
  """
  This will get all the store products and display them,
  as well as get the user's details to determine if they are
  a customer and if they have any orders or not.

  :param obj request: The user details

  :returns: the main store page
  """
  products = Product.objects.all()

  if request.user.is_authenticated:
    if not Customer.objects.filter(user=request.user).exists():
      Customer.objects.create(user=request.user)
    customer = request.user.customer
    order, created = Order.objects.get_or_create(customer=customer, order_complete=False)
    items = order.orderitem_set.all()
    cart_items = order.get_amount()
  else:
    items = []
    order = {'get_total': 0, 'get_amount': 0}
    cart_items = order['get_amount']
  
  return render(request, './store.html', {
    'products': products,
    'cartItems': cart_items
    })

def cart(request):
  """
  Gets all the products added to the cart by the
  user and displays them

  :param obj request: The user details

  :returns: returns cart items
  """
  products = Product.objects.all()

  if request.user.is_authenticated:
    customer = request.user.customer
    order, created = Order.objects.get_or_create(customer=customer, order_complete=False)
    items = order.orderitem_set.all()
  else:
    items = []
    order = {'get_total': 0, 'get_amount': 0}
  
  return render(request, './cart.html', {
    'items': items,
    'order': order,
  })

def checkout(request):
  """
  Gets the the products added to the cart and gets the
  total of these products. The user is then able to pay
  for them.

  :param obj request: The user details

  :returns: returns checkout items
  """
  if request.user.is_authenticated:
    customer = request.user.customer
    order, created = Order.objects.get_or_create(customer=customer, order_complete=False)
    items = order.orderitem_set.all()
  else:
      items = []
      order = {'get_total': 0, 'get_amount': 0}


  return render(request, './checkout.html', {
    'items': items,
    'order': order,
    })


def updateItem(request):
  """
  Allows the user to remove items from the cart
  """
  data = json.loads(request.body)
  productId = data['productId']
  action = data['action']

  customer = request.user.customer
  product = Product.objects.get(id=productId)
  order, created = Order.objects.get_or_create(customer=customer, order_complete=False)
  orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

  if action == 'remove':
    print('removing button')
    orderItem.delete()


def processOrder(request):
  """
  Process the user's payment and saves the date of the order
  """
  print('requesting prder')
  if request.user.is_authenticated:
    customer = request.user.customer
    order, created = Order.objects.get_or_create(customer=customer, order_complete=False)
    order.order_id = datetime.datetime.now().timestamp()
    order.order_complete = True
    order.save()

login/templates/authentication/login.html
<html>
    <head>
        <title>Login</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
    </head>
    
    <body class="container d-flex flex-column justify-content-center align-items-center vh-100">
        <h1> User Login </h1>
        <form action = "{% url 'user_auth:authenticate_user' %}" method="post">
            {% csrf_token %}
            
            <label class="form-label" for="username">Username</label>
            <input class="form-control" type="text" id="username" name="username" placeholder="User" required>
            <br/><br/>
        
            <label class="form-label" for="password">Password</label>
            <input class="form-control" type="password" id="password" name="password" required>
            <br/><br/>
        
            <input class="btn btn-outline-success rounded-0" type="submit" value="Login" />
        </form>
    </body>
</html>

register/templates/register/register.html
{% load crispy_forms_tags %}

<html>
  <head>
    <title>Register</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
  </head>
  
  <body class="container d-flex flex-column justify-content-center align-items-center vh-100">
  {% block title %}Create an Account{% endblock %}
  
  {% block content %}
      <form method="POST" class="form-group">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Register</button>
      </form>
  {% endblock %}
  </body>
</html>

store/templates/boilerplate.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>The Shopper</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">

  </head>
  <body>
    

    <main class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href={% url 'store:store' %}>The Shopper</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href={% url 'store:store' %}>Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href={% url 'store:cart' %}>Cart</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href={% url 'store:checkout' %}>Checkout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href={% url 'register:register' %}>Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href={% url 'user_auth:login' %}>Login</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      {% block content %}

      {% endblock content %}

    </main>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
  <script src="{% static 'javascript/cart.js' %}"></script>
  <script src="{% static 'javascript/checkout.js' %}"></script>
  <script>
    let user = '{{request.user}}'
  </script>
  <script>
    function getCookie(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
              const cookie = cookies[i].trim();
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');
  </script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  </body>
</html>

store/templates/cart.html
{% extends "boilerplate.html" %}
{% load static %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-4 my-3">
        <a class="btn btn-outline-primary" href="{% url 'store:store' %}"> &#x2190; Back to Shop</a>
      </div>
    </div>
    <div class="row gx-5">
      <div class="col-9">
        {% for item in items %}
          <div class="row border d-flex align-items-center py-1">
            <div class="col-3">
              <img src="{{item.product.image_link}}">
            </div>
            <div class="col-3">
              <h5>{{item.product.name}}</h5>
            </div>
            <div class="col-3">
              <h5>R{{item.product.price}}</h5>
            </div>
            <div class="col-3">
              <button class="btn update-cart" data-product={{item.product.id}} data-action="remove">
                <i class="bi bi-trash fs-4"></i>
              </button>
            </div>
          </div>
        {% endfor %}
        
      </div>
      <div class="col-3 border d-flex flex-column">
        <h4>Items: {{order.get_amount}}</h4>
        <h4>Total: R{{order.get_total}}</h4>
        <a class="col-4 btn btn-success" href="{% url 'store:checkout' %}" style="width: 100px">Checkout</a>
      </div>
    </div>
  </div>
{% endblock content %}

store/templates/checkout.html
{% extends "boilerplate.html" %}
{% load static %}

{% block content %}
  <div class="row mt-5 d-flex justify-content-center">
    <div class="row">
      <div class="col-4">
        <a class="btn btn-outline-primary" href="{% url 'store:cart' %}"> &#x2190; Back to Cart</a>
      </div>
    </div>
    <div class="col-3 border d-flex flex-column justify-content-center align-items-center p-5 m-5">
      <h4>Items: {{order.get_amount}}</h4>
      <h4>Total: R{{order.get_total}}</h4>
      <a class="col-4 btn btn-success purchase-btn" style="width: 100px">Purchase</a>
    </div>
  </div>
{% endblock content %}

store/templates/store.html
{% extends "boilerplate.html" %}
{% load static %}

{% block content %}
  <div class="row row-cols-1 row-cols-md-3 g-4 mt-4">
    {% for p in products %}
      <div class="col">
        <div class="card rounded-0 product h-100">
          <img src="{{p.image_link}}" class="card-img-top rounded-0" alt="...">
          <div class="card-body">
            <h5 class="card-title">{{p.name}}</h5>
            <hr>
            <div class="d-flex justify-content-between align-items-start mt-4 pe-4">
              <btn class="btn btn-success add-btn rounded-0 update-cart" data-product={{p.id}} data-action="add">Add to cart</btn>
              <h4 class="fs-3 text-success">R{{p.price}}</h4>
            </div>
          </div>
          <div class="card-footer">
            <small class="text-body-secondary">Added on {{p.created_at}}</small>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock content %}